apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-html-app
  labels:
    app: sample-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-html-app
  template:
    metadata:
      labels:
        app: sample-html-app
    spec:
      containers:
      - name: sample-html-app
        # image is replaced by pipeline (or kubectl set image)
        image: REPLACE_IMAGE
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-html-service
spec:
  type: NodePort
  selector:
    app: sample-html-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

